passage = str(input())
a = passage.replace('a','')
A = a.replace('A','')
e = A.replace('e','')
E = e.replace('E','')
i = E.replace('i','')
I = i.replace('I','')
o = I.replace('o','')
O = o.replace('O','')
u = O.replace('u','')
U = u.replace('U','')
print(U)